const SHAPES = [
  [/^\(\((.*)\)\)$/s, 'circle'],
  [/^\[\((.*)\)\]$/s, 'cylinder'],
  [/^\(\[(.*)\]\)$/s, 'oval'],
  [/^\[\[(.*)\]\]$/s, 'queue'],
  [/^\{(.*)\}$/s, 'diamond'],
  [/^\(>(.*)\)$/s, 'callout'],
  [/^\((.*)\)$/s, 'oval'],
  [/^\[\/(.*)\/\]$/s, 'parallelogram'],
  [/^\[\\(.*)\\\]$/s, 'parallelogram'],
  [/^\[(.*)\]$/s, 'rectangle'],
];

const quote = value => JSON.stringify(String(value).replace(/<br\s*\/?>/gi, '\\n'));
const safeId = value => quote(value.trim());

function stripFrontmatter(source) {
  return source.replace(/^---\s*\n[\s\S]*?\n---\s*\n?/, '');
}

function splitStatements(source) {
  const lines = source.replace(/\r\n?/g, '\n').split('\n');
  const out = [];
  for (let i = 0; i < lines.length; i++) {
    const line = lines[i].replace(/%%.*$/, '').trim();
    if (!line) continue;
    let current = '', depth = 0, quoteChar = null;
    for (const ch of line) {
      if (quoteChar) {
        current += ch;
        if (ch === quoteChar) quoteChar = null;
      } else if (ch === '"' || ch === "'") { quoteChar = ch; current += ch; }
      else if ('[({'.includes(ch)) { depth++; current += ch; }
      else if (']})'.includes(ch)) { depth--; current += ch; }
      else if (ch === ';' && depth === 0) { if (current.trim()) out.push({line:i+1,text:current.trim()}); current=''; }
      else current += ch;
    }
    if (current.trim()) out.push({line:i+1,text:current.trim()});
  }
  return out;
}

function parseNode(token) {
  const m = token.trim().match(/^([\w.-]+)\s*(.*)$/s);
  if (!m) return null;
  const id = m[1], suffix = m[2].trim();
  if (!suffix) return { id, label: id, shape: null };
  for (const [re, shape] of SHAPES) {
    const sm = suffix.match(re);
    if (sm) return { id, label: sm[1].replace(/^['"]|['"]$/g, ''), shape };
  }
  return null;
}

function edgeArrow(op) {
  const dotted = op.includes('.');
  const thick = op.includes('=');
  const left = op.startsWith('<');
  const right = op.endsWith('>') || op.includes('o') || op.includes('x');
  return { arrow: left && right ? '<->' : left ? '<-' : right ? '->' : '--', dotted, thick };
}

function parseEdge(statement) {
  const arrowRe = /\s*(<[-.=]+>|<[-.=]+|[-.=]+>|[-.=]+(?:o|x))\s*/g;
  const parts = [];
  let last = 0, m;
  while ((m = arrowRe.exec(statement))) {
    parts.push(statement.slice(last, m.index).trim(), m[1]);
    last = arrowRe.lastIndex;
  }
  parts.push(statement.slice(last).trim());
  if (parts.length < 3) return null;
  const result = [];
  for (let i = 0; i + 2 < parts.length; i += 2) {
    let lhs = parts[i], op = parts[i+1], rhs = parts[i+2], label = '';
    const pipe = rhs.match(/^\|([^|]*)\|\s*(.*)$/s);
    if (pipe) { label = pipe[1]; rhs = pipe[2]; }
    else {
      const mermaidLabel = rhs.match(/^([^\s]+)\s+--?\s+(.+)$/s);
      if (mermaidLabel && op.includes('-')) { label = mermaidLabel[1]; rhs = mermaidLabel[2]; }
    }
    const a = parseNode(lhs), b = parseNode(rhs);
    if (!a || !b) return null;
    result.push({ from:a, to:b, label, ...edgeArrow(op) });
    parts[i+2] = rhs;
  }
  return result;
}

function emitNode(node, indent) {
  const attrs = [];
  if (node.label !== node.id) attrs.push(`label: ${quote(node.label)}`);
  if (node.shape) attrs.push(`shape: ${node.shape}`);
  return attrs.length ? `${indent}${safeId(node.id)}: { ${attrs.join('; ')} }` : `${indent}${safeId(node.id)}`;
}

export function convertMermaidFlowchartToD2(source, options = {}) {
  source = stripFrontmatter(source);
  const statements = splitStatements(source);
  const warnings = [], output = [], declared = new Set(), containerStack = [];
  let direction = 'down';
  const header = statements.shift();
  const hm = header?.text.match(/^(?:flowchart|graph)\s+(TB|TD|BT|LR|RL)$/i);
  if (!hm) throw new Error('Only Mermaid flowchart/graph diagrams are supported');
  direction = ({TB:'down',TD:'down',BT:'up',LR:'right',RL:'left'})[hm[1].toUpperCase()];
  output.push(`# Generated by mmd2d2`, `direction: ${direction}`, '');

  const indent = () => '  '.repeat(containerStack.length);
  const declare = node => {
    const key = [...containerStack, node.id].join('.');
    if (!declared.has(key)) { output.push(emitNode(node, indent())); declared.add(key); }
  };

  for (const item of statements) {
    const s = item.text;
    let m;
    if ((m = s.match(/^subgraph\s+([^\s\[]+)?\s*(?:\[(.*)\])?$/i))) {
      const id = m[1] || `subgraph_${item.line}`, label = m[2] || id;
      output.push(`${indent()}${safeId(id)}: ${quote(label)} {`);
      containerStack.push(id);
      continue;
    }
    if (/^end$/i.test(s)) { if (!containerStack.length) warnings.push({line:item.line,message:'unmatched end'}); else { containerStack.pop(); output.push(`${indent()}}`); } continue; }
    if ((m = s.match(/^direction\s+(TB|TD|BT|LR|RL)$/i))) { output.push(`${indent()}direction: ${{TB:'down',TD:'down',BT:'up',LR:'right',RL:'left'}[m[1].toUpperCase()]}`); continue; }
    if (/^(classDef|class|style|linkStyle|click)\b/i.test(s)) { warnings.push({line:item.line,message:`styling or interaction omitted: ${s.split(/\s/)[0]}`}); continue; }

    const edges = parseEdge(s);
    if (edges) {
      for (const e of edges) {
        declare(e.from); declare(e.to);
        const attrs = [];
        if (e.dotted) attrs.push('style.stroke-dash: 4');
        if (e.thick) attrs.push('style.stroke-width: 3');
        const lbl = e.label ? `: ${quote(e.label)}` : '';
        const block = attrs.length ? ` { ${attrs.join('; ')} }` : '';
        output.push(`${indent()}${safeId(e.from.id)} ${e.arrow} ${safeId(e.to.id)}${lbl}${block}`);
      }
      continue;
    }
    const node = parseNode(s);
    if (node) { declare(node); continue; }
    warnings.push({line:item.line,message:`unsupported statement omitted: ${s}`});
  }
  while (containerStack.length) { containerStack.pop(); output.push(`${indent()}}`); }
  if (options.strict && warnings.length) throw new Error(warnings.map(w => `line ${w.line}: ${w.message}`).join('\n'));
  return { d2: output.join('\n') + '\n', warnings };
}
